spring:
  application:
    name: cpa-api
  datasource:
    url: jdbc:mysql://mysql:3306/cpa
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080

# base-url: localhost:8080/