spring:
  application:
    name: cpa-api
  datasource:
    url: jdbc:mysql://ds-cpa-db.cluster-cx4dqztdn4yr.us-east-1.rds.amazonaws.com:3306/cpa
    username: admin
    password: Pa$$w0rd123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:db/cpa_schema.sql

server:
  port: 8081